flist:
	vimdiff ../cva6/core/Flist.cv64a6_imafdc_sv39 design.flist 

ariane:
	vimdiff ../cva6/core/ariane.sv ariane.sv 

harness:
	vimdiff ../cva6/corev_apu/tb/ariane_testharness.sv  ariane_testharness.sv 

regfile:
	vimdiff ../cva6/core/ariane_regfile_ff.sv  ariane_regfile_ff.sv 
